#!/usr/bin/env bash

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

case "$1" in

run)
    bash "$BASE_DIR/core/engine.sh"
;;
live)
bash "$BASE_DIR/modules/live_dashboard.sh"
;;
daemon)
    bash "$BASE_DIR/core/syswatchd.sh"
;;

help|"")
    echo
    echo "SYSWATCH COMMANDS"
    echo
    echo "syswatch run        Run full security scan"
    echo "syswatch daemon     Start continuous monitoring"
    echo "syswatch help       Show this help menu"
    echo
;;

*)
    echo "Unknown command"
    echo "Run: syswatch help"
;;

esac
